twitter_consumer_key: qSXgYnfl9TQHL0rcRw
twitter_consumer_secret: zhzEDv12a87RimkvaisEi5IZvqISzEVmf2gDIJQCuw

facebook_app_id: 438992236120376
facebook_app_secret: 515d2129deab162281220da6e4d7eb05

twitter_oauth_token: 308762265-ahoa4FzpufTaPRghxHsChqwTwMRIRaJfHkmkn5Ip
twitter_oauth_token_secret: UwAWZJlhSGiBNgbHtDqiS2ILZJuprd091rUNbETE